// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReactiveUI.SourceGenerators.Models;

namespace ReactiveUI.SourceGenerators;

/// <summary>A source generator for generating reactiveObject properties.</summary>
public partial class ReactiveObjectGenerator
{
    /// <summary>Gets the generator type name used in generated-code metadata.</summary>
    internal static readonly string GeneratorName = typeof(ReactiveObjectGenerator).FullName!;

    /// <summary>Gets the generator assembly version used in generated-code metadata.</summary>
    internal static readonly string GeneratorVersion = typeof(ReactiveObjectGenerator).Assembly.GetName().Version.ToString();

    /// <summary>Creates metadata for a ReactiveObject-annotated class.</summary>
    /// <param name="context">The attribute syntax context for the class.</param>
    /// <param name="token">The cancellation token for the generator operation.</param>
    /// <returns>The class metadata, or <see langword="null"/> when not applicable.</returns>
    private static ReactiveObjectInfo? GetClassInfo(in GenericGeneratorAttributeSyntaxContext context, CancellationToken token)
    {
        if (!(context.TargetNode is ClassDeclarationSyntax declaredClass && declaredClass.Modifiers.Any(SyntaxKind.PartialKeyword)))
        {
            return default;
        }

        var symbol = context.TargetSymbol;
        token.ThrowIfCancellationRequested();

        if (symbol is not INamedTypeSymbol classSymbol)
        {
            return default;
        }

        token.ThrowIfCancellationRequested();

        // Get the containing type info
        var targetInfo = TargetInfo.From(classSymbol);

        token.ThrowIfCancellationRequested();
        return new(targetInfo);
    }

    /// <summary>Generates the complete source document for a ReactiveObject declaration.</summary>
    /// <param name="containingTypeName">The name of the containing type.</param>
    /// <param name="containingNamespace">The containing namespace.</param>
    /// <param name="containingClassVisibility">The containing type visibility.</param>
    /// <param name="containingType">The containing type kind.</param>
    /// <param name="integration">The selected ReactiveUI integration metadata.</param>
    /// <returns>The generated source document.</returns>
    private static string GenerateSource(
        string containingTypeName,
        string containingNamespace,
        string containingClassVisibility,
        string containingType,
        ReactiveUiIntegration integration) =>
        $$"""
// <auto-generated/>
#pragma warning disable
#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using System.ComponentModel;
{{integration.UsingDirectives}}

namespace {{containingNamespace}}
{
    /// <summary>
    /// Partial class for the {{containingTypeName}} which contains ReactiveUI IReactiveObject initialization.
    /// </summary>
    {{containingClassVisibility}} partial {{containingType}} {{containingTypeName}} : IReactiveObject
    {
{{IndentGeneratedMembers(ReactiveObjectSource.Members)}}
    }
}
#nullable restore
#pragma warning restore
""";

    /// <summary>Indents reusable generated members within their containing type.</summary>
    /// <param name="members">The generated members to indent.</param>
    /// <returns>The indented generated members.</returns>
    private static string IndentGeneratedMembers(string members)
    {
        var builder = new StringBuilder(members.Length);
        var atLineStart = true;
        foreach (var character in members)
        {
            if (atLineStart && character is not '\r' and not '\n')
            {
                _ = builder.Append("        ");
            }

            _ = builder.Append(character);
            atLineStart = character == '\n';
        }

        return builder.ToString();
    }

    /// <summary>Contains reusable generated ReactiveObject source fragments.</summary>
    private static class ReactiveObjectSource
    {
        /// <summary>Contains the generated ReactiveObject event implementation.</summary>
        internal const string Members = """
        private bool _propertyChangingEventsSubscribed;
        private bool _propertyChangedEventsSubscribed;

        /// <inheritdoc/>
        public event PropertyChangingEventHandler? PropertyChanging
        {
            add
            {
                if (!_propertyChangingEventsSubscribed)
                {
                    this.SubscribePropertyChangingEvents();
                    _propertyChangingEventsSubscribed = true;
                }

                PropertyChangingHandler += value;
            }
            remove => PropertyChangingHandler -= value;
        }

        /// <inheritdoc/>
        public event PropertyChangedEventHandler? PropertyChanged
        {
            add
            {
                if (!_propertyChangedEventsSubscribed)
                {
                    this.SubscribePropertyChangedEvents();
                    _propertyChangedEventsSubscribed = true;
                }

                PropertyChangedHandler += value;
            }
            remove => PropertyChangedHandler -= value;
        }

        [SuppressMessage("Roslynator", "RCS1159:Use EventHandler<T>", Justification = "Long term design.")]
        private event PropertyChangingEventHandler? PropertyChangingHandler;

        [SuppressMessage("Roslynator", "RCS1159:Use EventHandler<T>", Justification = "Long term design.")]
        private event PropertyChangedEventHandler? PropertyChangedHandler;

        /// <inheritdoc/>
        void IReactiveObject.RaisePropertyChanging(PropertyChangingEventArgs args) =>
            PropertyChangingHandler?.Invoke(this, args);

        /// <inheritdoc/>
        void IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args) =>
            PropertyChangedHandler?.Invoke(this, args);
        """;
    }
}
