//HintName: TestNs.TestVM.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_dates"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<global::System.DateTime>? Dates => _dates;
        /// <inheritdoc cref="_timestamps"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<global::System.DateTimeOffset>? Timestamps => _timestamps;
    }
}
#nullable restore
#pragma warning restore