//HintName: TestNs.ViewModel.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    internal partial class ViewModel
    {
        /// <inheritdoc cref="_theList"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<string>? TheList => _theList;
    }
}
#nullable restore
#pragma warning restore
