//HintName: TestNs.TestVM.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_publicItems"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<string>? PublicItems => _publicItems;
        /// <inheritdoc cref="_protectedItems"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected global::System.Collections.ObjectModel.ReadOnlyObservableCollection<string>? ProtectedItems => _protectedItems;
        /// <inheritdoc cref="_internalItems"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        internal global::System.Collections.ObjectModel.ReadOnlyObservableCollection<string>? InternalItems => _internalItems;
        /// <inheritdoc cref="_privateItems"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private global::System.Collections.ObjectModel.ReadOnlyObservableCollection<string>? PrivateItems => _privateItems;
        /// <inheritdoc cref="_internalProtectedItems"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected internal global::System.Collections.ObjectModel.ReadOnlyObservableCollection<string>? InternalProtectedItems => _internalProtectedItems;
        /// <inheritdoc cref="_privateProtectedItems"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private protected global::System.Collections.ObjectModel.ReadOnlyObservableCollection<string>? PrivateProtectedItems => _privateProtectedItems;
    }
}
#nullable restore
#pragma warning restore
