//HintName: TestNs.TestVM.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_names"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<string>? Names => _names;
        /// <inheritdoc cref="_numbers"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<int>? Numbers => _numbers;
        /// <inheritdoc cref="_values"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<double>? Values => _values;
    }
}
#nullable restore
#pragma warning restore