//HintName: TestNs.OuterVM+InnerVM.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class OuterVM
{

    public partial class InnerVM
    {
        /// <inheritdoc cref="_innerList"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<string>? InnerList => _innerList;
    }
}

}
#nullable restore
#pragma warning restore