//HintName: TestNs.GenericVM`1.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class GenericVM<T>
    {
        /// <inheritdoc cref="_items"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<T>? Items => _items;
    }
}
#nullable restore
#pragma warning restore