//HintName: TestNs.TestVM.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_tuples"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<(int Id, string Name)>? Tuples => _tuples;
    }
}
#nullable restore
#pragma warning restore