//HintName: TestNs.TestVM.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_statuses"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<global::TestNs.Status>? Statuses => _statuses;
    }
}
#nullable restore
#pragma warning restore