//HintName: TestNs.OuterVM+InnerVM+DeepInnerVM.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class OuterVM
{
public partial class InnerVM
{

    public partial class DeepInnerVM
    {
        /// <inheritdoc cref="_deepList"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<double>? DeepList => _deepList;
    }
}
}

}
#nullable restore
#pragma warning restore