//HintName: TestNs.OuterVM.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class OuterVM
    {
        /// <inheritdoc cref="_outerList"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<int>? OuterList => _outerList;
    }
}
#nullable restore
#pragma warning restore