//HintName: Namespace1.TestVM.BindableDerivedList.g.cs
// <auto-generated/>
using System.Collections.ObjectModel;
using DynamicData;
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace Namespace1
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_numbers"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ReadOnlyObservableCollection<int>? Numbers => _numbers;
    }
}
#nullable restore
#pragma warning restore