//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<string, string>? _processWithCancellationCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<string, string> ProcessWithCancellationCommand { get => _processWithCancellationCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask<string, string>(ProcessWithCancellation); }
    }
}
#nullable restore
#pragma warning restore