//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<string?, string?>? _processNullableCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<string?, string?> ProcessNullableCommand { get => _processNullableCommand ??= global::ReactiveUI.ReactiveCommand.Create<string?, string?>(ProcessNullable); }
        private global::ReactiveUI.ReactiveCommand<int?, int>? _processNullableIntCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<int?, int> ProcessNullableIntCommand { get => _processNullableIntCommand ??= global::ReactiveUI.ReactiveCommand.Create<int?, int>(ProcessNullableInt); }
    }
}
#nullable restore
#pragma warning restore