//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<(int number, string text), string>? _combineValuesCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<(int number, string text), string> CombineValuesCommand { get => _combineValuesCommand ??= global::ReactiveUI.ReactiveCommand.Create<(int number, string text), string>(CombineValues); }
    }
}
#nullable restore
#pragma warning restore