//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid>? _loadCommand;

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid> LoadCommand { get => _loadCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask(() => global::System.Threading.Tasks.Task.Run(() => Load())); }

        private global::ReactiveUI.ReactiveCommand<int, int>? _fetchCommand;

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<int, int> FetchCommand { get => _fetchCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask<int, int>((int p, global::System.Threading.CancellationToken ct) => global::System.Threading.Tasks.Task.Run(() => Fetch(p, ct), ct)); }

        private global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid>? _cancellableCommand;

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid> CancellableCommand { get => _cancellableCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask((global::System.Threading.CancellationToken ct) => global::System.Threading.Tasks.Task.Run(() => Cancellable(ct), ct)); }

        private global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid>? _crunchCommand;

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid> CrunchCommand { get => _crunchCommand ??= global::ReactiveUI.ReactiveCommand.CreateRunInBackground(Crunch, canExecute: null, backgroundScheduler: Worker); }
    }
}
#nullable restore
#pragma warning restore
