//HintName: TestNs.TestViewModel3+TestInnerClass2.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class TestViewModel3
{

    public partial class TestInnerClass2
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int>? _testI2Command;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int> TestI2Command { get => _testI2Command ??= global::ReactiveUI.ReactiveCommand.Create(TestI2); }
    }
}

}
#nullable restore
#pragma warning restore