//HintName: TestNs.TestViewModel3+TestInnerClass2+TestInnerClass3.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class TestViewModel3
{
public partial class TestInnerClass2
{

    public partial class TestInnerClass3
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int>? _testI3Command;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int> TestI3Command { get => _testI3Command ??= global::ReactiveUI.ReactiveCommand.Create(TestI3); }
    }
}
}

}
#nullable restore
#pragma warning restore