//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    /// <inheritdoc/>
    partial class TestVM
    {
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveCommandGenerator", "1.1.0.0")]
        private ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit>? _test1Command;
        public ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit> Test1Command { get => _test1Command ??= ReactiveUI.ReactiveCommand.CreateFromTask(Test1) ; }

        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "1.1.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Obsolete("Commands are initialized automatically. Method will be removed in future version.")]
        protected void InitializeCommands()
        {
        }
    }
}