//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<string, global::System.Reactive.Unit>? _test3Command;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<string, global::System.Reactive.Unit> Test3Command { get => _test3Command ??= global::ReactiveUI.ReactiveCommand.CreateFromTask<string>(Test3); }
    }
}
#nullable restore
#pragma warning restore