//HintName: TestNs.Outer+Middle.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class Outer
{

    public partial class Middle
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit>? _middleCommandCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit> MiddleCommandCommand { get => _middleCommandCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask(MiddleCommand); }
    }
}

}
#nullable restore
#pragma warning restore