//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, string?>? _getNullableStringCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, string?> GetNullableStringCommand { get => _getNullableStringCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask(GetNullableStringAsync); }
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int?>? _getNullableIntCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int?> GetNullableIntCommand { get => _getNullableIntCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask(GetNullableIntAsync); }
    }
}
#nullable restore
#pragma warning restore