//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit>? _doWorkCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit> DoWorkCommand { get => _doWorkCommand ??= global::ReactiveUI.ReactiveCommand.Create(DoWork, CanDoWork); }
    }
}
#nullable restore
#pragma warning restore