//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, (int Id, string Name)>? _getNamedTupleCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, (int Id, string Name)> GetNamedTupleCommand { get => _getNamedTupleCommand ??= global::ReactiveUI.ReactiveCommand.Create(GetNamedTuple); }
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, (bool Success, string Message)>? _getAsyncTupleCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, (bool Success, string Message)> GetAsyncTupleCommand { get => _getAsyncTupleCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask(GetAsyncTuple); }
    }
}
#nullable restore
#pragma warning restore