//HintName: TestNs.TestVMRecord.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial record TestVMRecord
    {
        private global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid>? _doSomethingCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid> DoSomethingCommand { get => _doSomethingCommand ??= global::ReactiveUI.ReactiveCommand.Create(DoSomething); }
        private global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, int>? _getValueCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, int> GetValueCommand { get => _getValueCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask(GetValueAsync); }
    }
}
#nullable restore
#pragma warning restore