//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::TestNs.Status, string>? _getStatusMessageCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::TestNs.Status, string> GetStatusMessageCommand { get => _getStatusMessageCommand ??= global::ReactiveUI.ReactiveCommand.Create<global::TestNs.Status, string>(GetStatusMessage); }
        private global::ReactiveUI.ReactiveCommand<global::TestNs.Status?, global::System.Reactive.Unit>? _setStatusCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::TestNs.Status?, global::System.Reactive.Unit> SetStatusCommand { get => _setStatusCommand ??= global::ReactiveUI.ReactiveCommand.Create<global::TestNs.Status?>(SetStatus); }
    }
}
#nullable restore
#pragma warning restore