//HintName: TestNs.GenericVM`1.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class GenericVM<T>
    {
        private global::ReactiveUI.ReactiveCommand<T?, T?>? _processItemCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<T?, T?> ProcessItemCommand { get => _processItemCommand ??= global::ReactiveUI.ReactiveCommand.Create<T?, T?>(ProcessItem); }
        private global::ReactiveUI.ReactiveCommand<T?, T?>? _processItemCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<T?, T?> ProcessItemCommand { get => _processItemCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask<T?, T?>(ProcessItemAsync); }
    }
}
#nullable restore
#pragma warning restore