//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Threading.Tasks.ValueTask>? _doValueTaskWorkCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Threading.Tasks.ValueTask> DoValueTaskWorkCommand { get => _doValueTaskWorkCommand ??= global::ReactiveUI.ReactiveCommand.Create(DoValueTaskWork); }
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Threading.Tasks.ValueTask<int>>? _getValueTaskResultCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Threading.Tasks.ValueTask<int>> GetValueTaskResultCommand { get => _getValueTaskResultCommand ??= global::ReactiveUI.ReactiveCommand.Create(GetValueTaskResult); }
    }
}
#nullable restore
#pragma warning restore