//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<int>>>? _getComplexDataCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<int>>> GetComplexDataCommand { get => _getComplexDataCommand ??= global::ReactiveUI.ReactiveCommand.Create(GetComplexData); }
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Collections.Generic.IReadOnlyList<string>>? _getAsyncComplexDataCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Collections.Generic.IReadOnlyList<string>> GetAsyncComplexDataCommand { get => _getAsyncComplexDataCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask(GetAsyncComplexData); }
    }
}
#nullable restore
#pragma warning restore