//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid>? _createCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid> CreateCommand { get => _createCommand ??= global::ReactiveUI.ReactiveCommand.Create(Create); }
        private global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid>? _saveCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid> SaveCommand { get => _saveCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask(Save, CanExecuteSave); }
        private global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid>? _deleteCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid> DeleteCommand { get => _deleteCommand ??= global::ReactiveUI.ReactiveCommand.Create(Delete, CanExecuteDelete); }
        private global::ReactiveUI.ReactiveCommand<int, int>? _calculateCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        internal global::ReactiveUI.ReactiveCommand<int, int> CalculateCommand { get => _calculateCommand ??= global::ReactiveUI.ReactiveCommand.Create<int, int>(Calculate); }
    }
}
#nullable restore
#pragma warning restore