//HintName: TestNs.Outer+Middle+Inner.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class Outer
{
public partial class Middle
{

    public partial class Inner
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int>? _innerCommandCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int> InnerCommandCommand { get => _innerCommandCommand ??= global::ReactiveUI.ReactiveCommand.Create(InnerCommand); }
    }
}
}

}
#nullable restore
#pragma warning restore