//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, string>? _executeWithSchedulerCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, string> ExecuteWithSchedulerCommand { get => _executeWithSchedulerCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromTask(ExecuteWithScheduler, CanExecuteCommand); }
    }
}
#nullable restore
#pragma warning restore