//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int>? _getObservableSequenceCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, int> GetObservableSequenceCommand { get => _getObservableSequenceCommand ??= global::ReactiveUI.ReactiveCommand.CreateFromObservable(GetObservableSequence); }
    }
}
#nullable restore
#pragma warning restore