//HintName: TestNs.Outer.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class Outer
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit>? _outerCommandCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit> OuterCommandCommand { get => _outerCommandCommand ??= global::ReactiveUI.ReactiveCommand.Create(OuterCommand); }
    }
}
#nullable restore
#pragma warning restore