//HintName: TestNs.TestVM.ReactiveCommands.g.cs
// <auto-generated/>

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        private global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit>? _protectedCommandCommand;


        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected global::ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit> ProtectedCommandCommand { get => _protectedCommandCommand ??= global::ReactiveUI.ReactiveCommand.Create(ProtectedCommand); }
    }
}
#nullable restore
#pragma warning restore