//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_mustBeSet"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public required string MustBeSet
        { 
            get => _mustBeSet;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_mustBeSet")]
            init
            {
                this.RaiseAndSetIfChanged(ref _mustBeSet, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore