//HintName: TestNs1.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs1
{
    
    public partial class TestVM
    {
        
        /// <inheritdoc cref="_name"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonIncludeAttribute()]
        public string? Name
        { 
            get => _name;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_name")]
            set
            {
                this.RaiseAndSetIfChanged(ref _name, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore