//HintName: TestNs1.TestViewModel3+TestInnerClass2+TestInnerClass3.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs1
{
    public partial class TestViewModel3
{
public partial class TestInnerClass2
{
    public partial class TestInnerClass3
    {
        
        /// <inheritdoc cref="_testInner3"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestInner3
        { 
            get => _testInner3;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_testInner3")]
            set
            {
                this.RaiseAndSetIfChanged(ref _testInner3, value);
            }
        }
        
        /// <inheritdoc cref="_testInner33"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestInner33
        { 
            get => _testInner33;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_testInner33")]
            set
            {
                this.RaiseAndSetIfChanged(ref _testInner33, value);
            }
        }


    }
}
}

}
#nullable restore
#pragma warning restore