//HintName: TestNs1.TestViewModel3+TestInnerClass2.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs1
{
    public partial class TestViewModel3
{

    public partial class TestInnerClass2
    {
        
        /// <inheritdoc cref="_testInner2"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestInner2
        { 
            get => _testInner2;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_testInner2")]
            set => this.RaiseAndSetIfChanged(ref _testInner2, value);
        }
        
        /// <inheritdoc cref="_testInner22"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestInner22
        { 
            get => _testInner22;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_testInner22")]
            set => this.RaiseAndSetIfChanged(ref _testInner22, value);
        }
    }
}

}
#nullable restore
#pragma warning restore