//HintName: TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
	/// <summary>
	/// Partial class for the TestVM which contains ReactiveUI Reactive property initialization.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "1.1.0.0")]
	public partial class TestVM
	{
		/// <inheritdoc cref="_test3"/>
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		[System.Text.Json.Serialization.JsonInclude]
		[System.Runtime.Serialization.DataMember]
		public int Test3
		{ 
			get => _test3;
			[global::System.Diagnostics.CodeAnalysis.MemberNotNull("_test3")]
			set => this.RaiseAndSetIfChanged(ref _test3, value);
		}
	}
}
#nullable restore
#pragma warning restore