//HintName: TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
	/// <summary>
	/// Partial class for the TestVM which contains ReactiveUI Reactive property initialization.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "1.1.0.0")]
	public partial class TestVM
	{
		/// <inheritdoc cref="_test2"/>
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		public int Test2
		{ 
			get => _test2;
			[global::System.Diagnostics.CodeAnalysis.MemberNotNull("_test2")]
			set => this.RaiseAndSetIfChanged(ref _test2, value);
		}
	}
}
#nullable restore
#pragma warning restore