//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_test3"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonIncludeAttribute()]
        public int Test3
        { 
            get => _test3;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_test3")]
            set
            {
                this.RaiseAndSetIfChanged(ref _test3, value);
            }
        }


    }
}
#nullable restore
#pragma warning restore