//HintName: TestNs1.TestViewModel3.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs1
{
    /// <summary>
    /// Partial class for the TestViewModel3 which contains ReactiveUI Reactive property initialization.
    /// </summary>
    public partial class TestViewModel3
    {
        
        /// <inheritdoc cref="_testVM3Property"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "2.2.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public float TestVM3Property
        { 
            get => _testVM3Property;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_testVM3Property")]
            set => this.RaiseAndSetIfChanged(ref _testVM3Property, value);
        }
        
        /// <inheritdoc cref="_testVM3Property2"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "2.2.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public float TestVM3Property2
        { 
            get => _testVM3Property2;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_testVM3Property2")]
            set => this.RaiseAndSetIfChanged(ref _testVM3Property2, value);
        }
    }
}
#nullable restore
#pragma warning restore