//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the TestVM which contains ReactiveUI Reactive property initialization.
    /// </summary>
    public partial class TestVM
    {
        
        /// <inheritdoc cref="this.value"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "2.2.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string Value
        { 
            get => value;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("this.value")]
            set => this.RaiseAndSetIfChanged(ref this.value, value);
        }
    }
}
#nullable restore
#pragma warning restore