//HintName: TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the TestVM which contains ReactiveUI Reactive property initialization.
    /// </summary>
    public partial class TestVM
    {
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "1.1.0.0")]
        /// <inheritdoc cref="_test3"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonIncludeAttribute()]
        public int Test3
        { 
            get => _test3;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_test3")]
            set => this.RaiseAndSetIfChanged(ref _test3, value);
        }
    }
}
#nullable restore
#pragma warning restore