//HintName: ReactiveUI.SourceGenerators.ReactiveAttribute.g.cs
// Copyright (c) 2025 .NET Foundation and Contributors. All rights reserved.
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;

// <auto-generated/>
#pragma warning disable
#nullable enable
namespace ReactiveUI.SourceGenerators;

/// <summary>
/// ReactiveAttribute.
/// </summary>
/// <seealso cref="Attribute" />
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
internal sealed class ReactiveAttribute : Attribute
{
    /// <summary>
    /// Gets the AccessModifier of the set property.
    /// </summary>
    /// <value>
    /// The AccessModifier of the set property.
    /// </value>
    public AccessModifier SetModifier { get; init; }

    /// <summary>
    /// Gets the InheritanceModifier of the property.
    /// </sumary>
    public InheritanceModifier Inheritance { get; init; }

    /// <summary>
    /// Use Required attribute to indicate that the property is required.
    /// </summary>
    public bool UseRequired { get; init; }
}
#nullable restore
#pragma warning restore