//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the TestVM which contains ReactiveUI Reactive property initialization.
    /// </summary>
    public partial class TestVM
    {
        /// <inheritdoc cref="_mustBeSet"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string MustBeSet
        { 
            get => _mustBeSet;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_mustBeSet")]
            set => this.RaiseAndSetIfChanged(ref _mustBeSet, value);
        }
    }
}
#nullable restore
#pragma warning restore