//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_test1"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test1
        { 
            get => _test1;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_test1")]
            set
            {
                this.RaiseAndSetIfChanged(ref _test1, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore