//HintName: TestNs.TestVM.Properties.g.cs
using ReactiveUI;
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    /// <inheritdoc/>
    partial class TestVM
    {
        /// <inheritdoc cref="_test1"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "1.1.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test1 { get => _test1; set => this.RaiseAndSetIfChanged(ref _test1, value) ; }
    }
}