//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        
        /// <inheritdoc cref="_mustBeSet"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string MustBeSet
        { 
            get => _mustBeSet;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_mustBeSet")]
            set => this.RaiseAndSetIfChanged(ref _mustBeSet, value);
        }
    }
}
#nullable restore
#pragma warning restore