//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_test4"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test4
        { 
            get => _test4;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_test4")]
            set
            {
                this.RaiseAndSetIfChanged(ref _test4, value);
                this.RaisePropertyChanged(nameof(OtherNotifyProperty));
            }
        }
    }
}
#nullable restore
#pragma warning restore