//HintName: TestNs.GenericVM`2.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class GenericVM<TKey, TValue>
    {
        
        /// <inheritdoc cref="_key"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public TKey? Key
        { 
            get => _key;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_key")]
            set
            {
                this.RaiseAndSetIfChanged(ref _key, value);
            }
        }
        
        /// <inheritdoc cref="_value"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public TValue? Value
        { 
            get => _value;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_value")]
            set
            {
                this.RaiseAndSetIfChanged(ref _value, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore