//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_items"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.Generic.List<string>? Items
        { 
            get => _items;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_items")]
            set
            {
                this.RaiseAndSetIfChanged(ref _items, value);
            }
        }
        
        /// <inheritdoc cref="_mappings"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.Generic.Dictionary<int, string>? Mappings
        { 
            get => _mappings;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_mappings")]
            set
            {
                this.RaiseAndSetIfChanged(ref _mappings, value);
            }
        }
        
        /// <inheritdoc cref="_numbers"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.Generic.IEnumerable<int>? Numbers
        { 
            get => _numbers;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_numbers")]
            set
            {
                this.RaiseAndSetIfChanged(ref _numbers, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore