//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_bytes"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public byte[]? Bytes
        { 
            get => _bytes;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_bytes")]
            set
            {
                this.RaiseAndSetIfChanged(ref _bytes, value);
            }
        }
        
        /// <inheritdoc cref="_strings"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string[]? Strings
        { 
            get => _strings;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_strings")]
            set
            {
                this.RaiseAndSetIfChanged(ref _strings, value);
            }
        }
        
        /// <inheritdoc cref="_jaggedArray"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int[][]? JaggedArray
        { 
            get => _jaggedArray;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_jaggedArray")]
            set
            {
                this.RaiseAndSetIfChanged(ref _jaggedArray, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore