//HintName: TestNs.BaseVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class BaseVM
    {
        
        /// <inheritdoc cref="_shadowedProp"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? ShadowedProp
        { 
            get => _shadowedProp;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_shadowedProp")]
            set
            {
                this.RaiseAndSetIfChanged(ref _shadowedProp, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore