//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_lazyString"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Lazy<string>? LazyString
        { 
            get => _lazyString;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_lazyString")]
            set
            {
                this.RaiseAndSetIfChanged(ref _lazyString, value);
            }
        }
        
        /// <inheritdoc cref="_lazyInt"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Lazy<int>? LazyInt
        { 
            get => _lazyInt;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_lazyInt")]
            set
            {
                this.RaiseAndSetIfChanged(ref _lazyInt, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore