//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_item"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.IItem? Item
        { 
            get => _item;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_item")]
            set
            {
                this.RaiseAndSetIfChanged(ref _item, value);
            }
        }
        
        /// <inheritdoc cref="_disposable"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.IDisposable? Disposable
        { 
            get => _disposable;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_disposable")]
            set
            {
                this.RaiseAndSetIfChanged(ref _disposable, value);
            }
        }
        
        /// <inheritdoc cref="_list"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.Generic.IList<int>? List
        { 
            get => _list;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_list")]
            set
            {
                this.RaiseAndSetIfChanged(ref _list, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore