//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_firstName"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? FirstName
        { 
            get => _firstName;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_firstName")]
            set
            {
                this.RaiseAndSetIfChanged(ref _firstName, value);
                this.RaisePropertyChanged(nameof(FullName));
                this.RaisePropertyChanged(nameof(DisplayName));
            }
        }
        
        /// <inheritdoc cref="_lastName"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? LastName
        { 
            get => _lastName;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_lastName")]
            set
            {
                this.RaiseAndSetIfChanged(ref _lastName, value);
                this.RaisePropertyChanged(nameof(FullName));
                this.RaisePropertyChanged(nameof(DisplayName));
            }
        }
    }
}
#nullable restore
#pragma warning restore