//HintName: TestNs.Level1+Level2.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class Level1
{
    public partial class Level2
    {
        
        /// <inheritdoc cref="_level2Prop"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Level2Prop
        { 
            get => _level2Prop;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_level2Prop")]
            set
            {
                this.RaiseAndSetIfChanged(ref _level2Prop, value);
            }
        }
    }
}

}
#nullable restore
#pragma warning restore