//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_publicSet"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? PublicSet
        { 
            get => _publicSet;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_publicSet")]
            set
            {
                this.RaiseAndSetIfChanged(ref _publicSet, value);
            }
        }
        
        /// <inheritdoc cref="_protectedSet"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? ProtectedSet
        { 
            get => _protectedSet;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_protectedSet")]
            set
            {
                this.RaiseAndSetIfChanged(ref _protectedSet, value);
            }
        }
        
        /// <inheritdoc cref="_internalSet"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? InternalSet
        { 
            get => _internalSet;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_internalSet")]
            set
            {
                this.RaiseAndSetIfChanged(ref _internalSet, value);
            }
        }
        
        /// <inheritdoc cref="_privateSet"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? PrivateSet
        { 
            get => _privateSet;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_privateSet")]
            set
            {
                this.RaiseAndSetIfChanged(ref _privateSet, value);
            }
        }
        
        /// <inheritdoc cref="_internalProtectedSet"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? InternalProtectedSet
        { 
            get => _internalProtectedSet;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_internalProtectedSet")]
            set
            {
                this.RaiseAndSetIfChanged(ref _internalProtectedSet, value);
            }
        }
        
        /// <inheritdoc cref="_privateProtectedSet"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? PrivateProtectedSet
        { 
            get => _privateProtectedSet;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_privateProtectedSet")]
            set
            {
                this.RaiseAndSetIfChanged(ref _privateProtectedSet, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore