//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_location"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.Point Location
        {
            get => _location;
            set
            {
                this.RaiseAndSetIfChanged(ref _location, value);
            }
        }
        
        /// <inheritdoc cref="_optionalLocation"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.Point? OptionalLocation
        { 
            get => _optionalLocation;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_optionalLocation")]
            set
            {
                this.RaiseAndSetIfChanged(ref _optionalLocation, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore