//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_namedTuple"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public (int Id, string Name)? NamedTuple
        { 
            get => _namedTuple;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_namedTuple")]
            set
            {
                this.RaiseAndSetIfChanged(ref _namedTuple, value);
            }
        }
        
        /// <inheritdoc cref="_tuple"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Tuple<int, string>? Tuple
        { 
            get => _tuple;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_tuple")]
            set
            {
                this.RaiseAndSetIfChanged(ref _tuple, value);
            }
        }
        
        /// <inheritdoc cref="_valueTuple"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public (string, int, bool) ValueTuple
        { 
            get => _valueTuple;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_valueTuple")]
            set
            {
                this.RaiseAndSetIfChanged(ref _valueTuple, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore