//HintName: TestNs.Level1+Level2+Level3.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class Level1
{
public partial class Level2
{
    public partial class Level3
    {
        
        /// <inheritdoc cref="_level3Prop"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Level3Prop
        { 
            get => _level3Prop;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_level3Prop")]
            set
            {
                this.RaiseAndSetIfChanged(ref _level3Prop, value);
            }
        }
    }
}
}

}
#nullable restore
#pragma warning restore