//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_action"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Action? Action
        { 
            get => _action;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_action")]
            set
            {
                this.RaiseAndSetIfChanged(ref _action, value);
            }
        }
        
        /// <inheritdoc cref="_func"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Func<int, string>? Func
        { 
            get => _func;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_func")]
            set
            {
                this.RaiseAndSetIfChanged(ref _func, value);
            }
        }
        
        /// <inheritdoc cref="_handler"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.EventHandler? Handler
        { 
            get => _handler;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_handler")]
            set
            {
                this.RaiseAndSetIfChanged(ref _handler, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore