//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_userName"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonIncludeAttribute()]
        [global::System.Text.Json.Serialization.JsonPropertyNameAttribute("user_name")]
        public string? UserName
        { 
            get => _userName;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_userName")]
            set
            {
                this.RaiseAndSetIfChanged(ref _userName, value);
            }
        }
        
        /// <inheritdoc cref="_password"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Runtime.Serialization.IgnoreDataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonIgnoreAttribute()]
        public string? Password
        { 
            get => _password;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_password")]
            set
            {
                this.RaiseAndSetIfChanged(ref _password, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore