//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_point"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.ImmutablePoint Point
        {
            get => _point;
            set
            {
                this.RaiseAndSetIfChanged(ref _point, value);
            }
        }
        
        /// <inheritdoc cref="_optionalPoint"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.ImmutablePoint? OptionalPoint
        { 
            get => _optionalPoint;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_optionalPoint")]
            set
            {
                this.RaiseAndSetIfChanged(ref _optionalPoint, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore