//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_nullableInt"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int? NullableInt
        { 
            get => _nullableInt;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_nullableInt")]
            set
            {
                this.RaiseAndSetIfChanged(ref _nullableInt, value);
            }
        }
        
        /// <inheritdoc cref="_nullableDateTime"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.DateTime? NullableDateTime
        { 
            get => _nullableDateTime;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_nullableDateTime")]
            set
            {
                this.RaiseAndSetIfChanged(ref _nullableDateTime, value);
            }
        }
        
        /// <inheritdoc cref="_nullableGuid"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Guid? NullableGuid
        { 
            get => _nullableGuid;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_nullableGuid")]
            set
            {
                this.RaiseAndSetIfChanged(ref _nullableGuid, value);
            }
        }
        
        /// <inheritdoc cref="_nullableDecimal"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public decimal? NullableDecimal
        { 
            get => _nullableDecimal;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_nullableDecimal")]
            set
            {
                this.RaiseAndSetIfChanged(ref _nullableDecimal, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore