//HintName: TestNs.TestVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class TestVM
    {
        
        /// <inheritdoc cref="_status"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.Status Status
        {
            get => _status;
            set
            {
                this.RaiseAndSetIfChanged(ref _status, value);
            }
        }
        
        /// <inheritdoc cref="_nullableStatus"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.Status? NullableStatus
        { 
            get => _nullableStatus;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_nullableStatus")]
            set
            {
                this.RaiseAndSetIfChanged(ref _nullableStatus, value);
            }
        }
        
        /// <inheritdoc cref="_permissions"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.Permissions Permissions
        {
            get => _permissions;
            set
            {
                this.RaiseAndSetIfChanged(ref _permissions, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore