//HintName: TestNs.BaseVM.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class BaseVM
    {
        
        /// <inheritdoc cref="_baseName"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? BaseName
        { 
            get => _baseName;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_baseName")]
            set
            {
                this.RaiseAndSetIfChanged(ref _baseName, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore