//HintName: TestNs.GenericVM`1.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
        public partial class GenericVM<T>
    {
        
        /// <inheritdoc cref="_item"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public T? Item
        { 
            get => _item;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_item")]
            set
            {
                this.RaiseAndSetIfChanged(ref _item, value);
            }
        }
        
        /// <inheritdoc cref="_count"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Count
        { 
            get => _count;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_count")]
            set
            {
                this.RaiseAndSetIfChanged(ref _count, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore