//HintName: TestNs.Level1+Level2+Level3+Level4.Properties.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class Level1
{
public partial class Level2
{
public partial class Level3
{
    public partial class Level4
    {
        
        /// <inheritdoc cref="_level4Prop"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Level4Prop
        { 
            get => _level4Prop;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_level4Prop")]
            set
            {
                this.RaiseAndSetIfChanged(ref _level4Prop, value);
            }
        }
    }
}
}
}

}
#nullable restore
#pragma warning restore