//HintName: TestNs.View2.IViewFor.g.cs
// <auto-generated/>
using ReactiveUI;
using System.Windows;

#pragma warning disable
#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the View2 which contains ReactiveUI IViewFor initialization.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class View2 : IViewFor<TestNs.ViewModel2>
    {
        /// <summary>
        /// The view model dependency property.
        /// </summary>
        public static readonly DependencyProperty ViewModelProperty = DependencyProperty.Register(nameof(ViewModel), typeof(TestNs.ViewModel2), typeof(View2), new PropertyMetadata(null));

        /// <summary>
        /// Gets the binding root view model.
        /// </summary>
        public TestNs.ViewModel2 BindingRoot => ViewModel;

        /// <inheritdoc/>
        public TestNs.ViewModel2 ViewModel { get => (TestNs.ViewModel2)GetValue(ViewModelProperty); set => SetValue(ViewModelProperty, value); }

        /// <inheritdoc/>
        object? IViewFor.ViewModel { get => ViewModel; set => ViewModel = (TestNs.ViewModel2)value; }
    }
}
#nullable restore
#pragma warning restore