//HintName: TestNs.ReactivePropertiesView.IViewFor.g.cs
// <auto-generated/>
using ReactiveUI;
using System.Windows;

#pragma warning disable
#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the ReactivePropertiesView which contains ReactiveUI IViewFor initialization.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class ReactivePropertiesView : IViewFor<TestNs.ReactivePropertiesViewModel>
    {
        /// <summary>
        /// The view model dependency property.
        /// </summary>
        public static readonly DependencyProperty ViewModelProperty = DependencyProperty.Register(nameof(ViewModel), typeof(TestNs.ReactivePropertiesViewModel), typeof(ReactivePropertiesView), new PropertyMetadata(null));

        /// <summary>
        /// Gets the binding root view model.
        /// </summary>
        public TestNs.ReactivePropertiesViewModel BindingRoot => ViewModel;

        /// <inheritdoc/>
        public TestNs.ReactivePropertiesViewModel ViewModel { get => (TestNs.ReactivePropertiesViewModel)GetValue(ViewModelProperty); set => SetValue(ViewModelProperty, value); }

        /// <inheritdoc/>
        object? IViewFor.ViewModel { get => ViewModel; set => ViewModel = (TestNs.ReactivePropertiesViewModel)value; }
    }
}
#nullable restore
#pragma warning restore