//HintName: TestNs.StringItemView.IViewFor.g.cs
// <auto-generated/>
using ReactiveUI;
using System.Windows;

#pragma warning disable
#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the StringItemView which contains ReactiveUI IViewFor initialization.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class StringItemView : IViewFor<TestNs.GenericViewModel<string>>
    {
        /// <summary>
        /// The view model dependency property.
        /// </summary>
        public static readonly DependencyProperty ViewModelProperty = DependencyProperty.Register(nameof(ViewModel), typeof(TestNs.GenericViewModel<string>), typeof(StringItemView), new PropertyMetadata(null));

        /// <summary>
        /// Gets the binding root view model.
        /// </summary>
        public TestNs.GenericViewModel<string> BindingRoot => ViewModel;

        /// <inheritdoc/>
        public TestNs.GenericViewModel<string> ViewModel { get => (TestNs.GenericViewModel<string>)GetValue(ViewModelProperty); set => SetValue(ViewModelProperty, value); }

        /// <inheritdoc/>
        object? IViewFor.ViewModel { get => ViewModel; set => ViewModel = (TestNs.GenericViewModel<string>)value; }
    }
}
#nullable restore
#pragma warning restore