//HintName: TestNs.View1.IViewFor.g.cs
// <auto-generated/>
using ReactiveUI;
using System.Windows;

#pragma warning disable
#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the View1 which contains ReactiveUI IViewFor initialization.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class View1 : IViewFor<TestNs.ViewModel1>
    {
        /// <summary>
        /// The view model dependency property.
        /// </summary>
        public static readonly DependencyProperty ViewModelProperty = DependencyProperty.Register(nameof(ViewModel), typeof(TestNs.ViewModel1), typeof(View1), new PropertyMetadata(null));

        /// <summary>
        /// Gets the binding root view model.
        /// </summary>
        public TestNs.ViewModel1 BindingRoot => ViewModel;

        /// <inheritdoc/>
        public TestNs.ViewModel1 ViewModel { get => (TestNs.ViewModel1)GetValue(ViewModelProperty); set => SetValue(ViewModelProperty, value); }

        /// <inheritdoc/>
        object? IViewFor.ViewModel { get => ViewModel; set => ViewModel = (TestNs.ViewModel1)value; }
    }
}
#nullable restore
#pragma warning restore