//HintName: ReactiveUI.ReactiveUISourceGeneratorsExtensions.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using global::ReactiveUI;
using global::Splat;

namespace ReactiveUI.SourceGenerators
{
    /// <summary>
    /// Source-generated registration extensions for ReactiveUI views.
    /// </summary>
    internal static class ReactiveUISourceGeneratorsExtensions
    {
        public static void RegisterViewsForViewModelsSourceGenerated(this global::Splat.IMutableDependencyResolver resolver)
        {
            if (resolver is null) throw new global::System.ArgumentNullException(nameof(resolver));
        }
    }
}
#nullable restore
#pragma warning restore