//HintName: Views.ProductView.IViewFor.g.cs
// <auto-generated/>
using ReactiveUI;
using System.Windows;

#pragma warning disable
#nullable enable

namespace Views
{
    /// <summary>
    /// Partial class for the ProductView which contains ReactiveUI IViewFor initialization.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class ProductView : IViewFor<ViewModels.ProductViewModel>
    {
        /// <summary>
        /// The view model dependency property.
        /// </summary>
        public static readonly DependencyProperty ViewModelProperty = DependencyProperty.Register(nameof(ViewModel), typeof(ViewModels.ProductViewModel), typeof(ProductView), new PropertyMetadata(null));

        /// <summary>
        /// Gets the binding root view model.
        /// </summary>
        public ViewModels.ProductViewModel BindingRoot => ViewModel;

        /// <inheritdoc/>
        public ViewModels.ProductViewModel ViewModel { get => (ViewModels.ProductViewModel)GetValue(ViewModelProperty); set => SetValue(ViewModelProperty, value); }

        /// <inheritdoc/>
        object? IViewFor.ViewModel { get => ViewModel; set => ViewModel = (ViewModels.ProductViewModel)value; }
    }
}
#nullable restore
#pragma warning restore