//HintName: App.Views.ExternalView.IViewFor.g.cs
// <auto-generated/>
using ReactiveUI;
using System.Windows;

#pragma warning disable
#nullable enable

namespace App.Views
{
    /// <summary>
    /// Partial class for the ExternalView which contains ReactiveUI IViewFor initialization.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class ExternalView : IViewFor<External.ViewModels.ExternalViewModel>
    {
        /// <summary>
        /// The view model dependency property.
        /// </summary>
        public static readonly DependencyProperty ViewModelProperty = DependencyProperty.Register(nameof(ViewModel), typeof(External.ViewModels.ExternalViewModel), typeof(ExternalView), new PropertyMetadata(null));

        /// <summary>
        /// Gets the binding root view model.
        /// </summary>
        public External.ViewModels.ExternalViewModel BindingRoot => ViewModel;

        /// <inheritdoc/>
        public External.ViewModels.ExternalViewModel ViewModel { get => (External.ViewModels.ExternalViewModel)GetValue(ViewModelProperty); set => SetValue(ViewModelProperty, value); }

        /// <inheritdoc/>
        object? IViewFor.ViewModel { get => ViewModel; set => ViewModel = (External.ViewModels.ExternalViewModel)value; }
    }
}
#nullable restore
#pragma warning restore