//HintName: TestNs.Level1+Level2.IReactiveObject.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using System.ComponentModel;
using ReactiveUI;

namespace TestNs
{
    /// <summary>
    /// Partial class for the Level2 which contains ReactiveUI IReactiveObject initialization.
    /// </summary>
    public partial class Level2 : IReactiveObject
    {
        private bool _propertyChangingEventsSubscribed;
        private bool _propertyChangedEventsSubscribed;

        /// <inheritdoc/>
        public event PropertyChangingEventHandler? PropertyChanging
        {
            add
            {
                if (!_propertyChangingEventsSubscribed)
                {
                    this.SubscribePropertyChangingEvents();
                    _propertyChangingEventsSubscribed = true;
                }

                PropertyChangingHandler += value;
            }
            remove => PropertyChangingHandler -= value;
        }

        /// <inheritdoc/>
        public event PropertyChangedEventHandler? PropertyChanged
        {
            add
            {
                if (!_propertyChangedEventsSubscribed)
                {
                    this.SubscribePropertyChangedEvents();
                    _propertyChangedEventsSubscribed = true;
                }

                PropertyChangedHandler += value;
            }
            remove => PropertyChangedHandler -= value;
        }

        [SuppressMessage("Roslynator", "RCS1159:Use EventHandler<T>", Justification = "Long term design.")]
        private event PropertyChangingEventHandler? PropertyChangingHandler;

        [SuppressMessage("Roslynator", "RCS1159:Use EventHandler<T>", Justification = "Long term design.")]
        private event PropertyChangedEventHandler? PropertyChangedHandler;

        /// <inheritdoc/>
        void IReactiveObject.RaisePropertyChanging(PropertyChangingEventArgs args) =>
            PropertyChangingHandler?.Invoke(this, args);

        /// <inheritdoc/>
        void IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args) =>
            PropertyChangedHandler?.Invoke(this, args);
    }
}
#nullable restore
#pragma warning restore