// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Runtime.CompilerServices;
using System.Text;
using ReactiveUI.SourceGenerators.Models;

namespace ReactiveUI.SourceGenerators.CodeGeneration;

/// <summary>The C# constructs generated code is built from, each written through a <see cref="SourceWriter"/>.</summary>
/// <remarks>
/// Each member names one construct - a file header, a namespace, a partial type, a doc comment - and writes its fixed
/// text and its braces, so an emitter says what it builds and the layout follows from the writer's level. Every
/// generated file is block-scoped and free of file-scoped namespaces, so it compiles at the consumer's minimum C# version.
/// </remarks>
internal static class SourceWriterExtensions
{
    /// <summary>The marker that tells analyzers and the IDE a file is generated.</summary>
    internal const string AutoGeneratedMarker = "// <auto-generated/>";

    /// <summary>The attribute that keeps generated members out of the consumer's code coverage.</summary>
    internal const string ExcludeFromCodeCoverageAttribute = "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]";

    /// <summary>The encoding generated sources are handed to the compiler in: UTF-8 without a byte order mark.</summary>
    internal static readonly UTF8Encoding Utf8WithoutBom = new(encoderShouldEmitUTF8Identifier: false);

    /// <summary>Writes C# constructs through a writer.</summary>
    /// <param name="writer">The writer the construct is written to.</param>
    extension(SourceWriter writer)
    {
        /// <summary>Writes <c>// &lt;auto-generated/&gt;</c>.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter AutoGenerated() => writer.Line(AutoGeneratedMarker);

        /// <summary>Writes a <c>using</c> directive.</summary>
        /// <param name="namespaceName">The imported namespace.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Using(string namespaceName) => writer.Append("using ").Append(namespaceName).Line(";");

        /// <summary>Writes <c>#pragma warning disable</c> and <c>#nullable enable</c>, which open most generated files.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter DisableWarningsEnableNullable() => writer.Line("#pragma warning disable").Line("#nullable enable");

        /// <summary>Writes <c>#nullable restore</c> and <c>#pragma warning restore</c>, which close most generated files.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter RestoreNullableAndWarnings() => writer.Line("#nullable restore").Line("#pragma warning restore");

        /// <summary>Opens a block-scoped namespace, the only form C# 7.3 parses; the global namespace opens nothing.</summary>
        /// <param name="namespaceName">The namespace, or an empty string for the global namespace.</param>
        /// <returns>The number of blocks opened: one, or zero for the global namespace.</returns>
        internal int OpenNamespace(string namespaceName)
        {
            if (namespaceName.Length == 0)
            {
                return 0;
            }

            _ = writer.Append("namespace ").Line(namespaceName).OpenBlock();
            return 1;
        }

        /// <summary>Opens the partial declarations of every type containing a nested target, outermost first.</summary>
        /// <param name="containingType">The target's containing type, or <see langword="null"/> for a top-level target.</param>
        /// <returns>The number of blocks opened.</returns>
        internal int OpenContainingTypes(TargetInfo? containingType)
        {
            if (containingType is null)
            {
                return 0;
            }

            var depth = writer.OpenContainingTypes(containingType.ParentInfo);
            _ = writer.OpenPartialType(containingType);
            return depth + 1;
        }

        /// <summary>Opens a target type's partial declaration, <c>{visibility} partial {kind} {name}</c>.</summary>
        /// <param name="target">The target type.</param>
        /// <returns>The writer, inside the type's body.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter OpenPartialType(TargetInfo target) => writer.BeginPartialType(target).EndLine().OpenBlock();

        /// <summary>Opens a target type's partial declaration with a base list, <c>{visibility} partial {kind} {name} : {baseList}</c>.</summary>
        /// <param name="target">The target type.</param>
        /// <param name="baseList">The base types and interfaces, without the colon.</param>
        /// <returns>The writer, inside the type's body.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter OpenPartialType(TargetInfo target, string baseList) =>
            writer.BeginPartialType(target).Append(" : ").Line(baseList).OpenBlock();

        /// <summary>Starts a target type's partial declaration, for the caller to finish the line.</summary>
        /// <param name="target">The target type.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter BeginPartialType(TargetInfo target) =>
            writer.Append(target.TargetVisibility).Append(" partial ").Append(target.TargetType).Append(' ').Append(target.TargetName);

        /// <summary>Closes the given number of brace blocks.</summary>
        /// <param name="count">The number of blocks to close.</param>
        /// <returns>The writer.</returns>
        internal SourceWriter CloseBlocks(int count)
        {
            for (var i = 0; i < count; i++)
            {
                _ = writer.CloseBlock();
            }

            return writer;
        }

        /// <summary>Writes a one-line summary doc comment.</summary>
        /// <param name="text">The summary, already XML-safe.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Summary(string text) => writer.Line("/// <summary>").Append("/// ").Line(text).Line("/// </summary>");

        /// <summary>Writes <c>/// &lt;inheritdoc/&gt;</c>.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter InheritDoc() => writer.Line("/// <inheritdoc/>");

        /// <summary>Writes <c>/// &lt;inheritdoc cref="..."/&gt;</c>.</summary>
        /// <param name="cref">The referenced member.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter InheritDoc(string cref) => writer.Append("/// <inheritdoc cref=\"").Append(cref).Line("\"/>");

        /// <summary>Ends a statement.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter EndStatement() => writer.Line(";");

        /// <summary>Writes the attribute that keeps a generated member out of code coverage.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter ExcludeFromCodeCoverage() => writer.Line(ExcludeFromCodeCoverageAttribute);
    }

    /// <summary>Builds the <c>GeneratedCode</c> attribute line a generator stamps on its members.</summary>
    /// <param name="generatorName">The generator's full type name.</param>
    /// <param name="generatorVersion">The generator assembly's version.</param>
    /// <returns>The attribute, built once per generator rather than once per member.</returns>
    internal static string GeneratedCodeAttribute(string generatorName, string generatorVersion) =>
        $"[global::System.CodeDom.Compiler.GeneratedCode(\"{generatorName}\", \"{generatorVersion}\")]";
}
