//HintName: TestNs.GenericVM`1.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class GenericVM<T>
    {
        /// <inheritdoc cref="_itemHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<T?> _itemHelper;

        /// <inheritdoc cref="_item"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public T? Item { get => _item = (_itemHelper == null ? _item : _itemHelper.Value); }
    }
}
#nullable restore
#pragma warning restore