//HintName: TestNs.TestVMRecord.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial record TestVMRecord
    {
        /// <inheritdoc cref="CountObservableProperty"/>
        private int _countObservableProperty;

        /// <inheritdoc cref="_countObservablePropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<int>? _countObservablePropertyHelper;

        /// <inheritdoc cref="_countObservableProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int CountObservableProperty { get => _countObservableProperty = _countObservablePropertyHelper?.Value ?? _countObservableProperty; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _countObservablePropertyHelper = CountObservable!.ToProperty(this, nameof(CountObservableProperty));
        }
    }
}
#nullable restore
#pragma warning restore