//HintName: TestNs.Level1+Level2+Level3+Level4.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class Level1
{
public partial class Level2
{
public partial class Level3
{

    public partial class Level4
    {
        /// <inheritdoc cref="DeepObservableProperty"/>
        private bool _deepObservableProperty;

        /// <inheritdoc cref="_deepObservablePropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<bool>? _deepObservablePropertyHelper;

        /// <inheritdoc cref="_deepObservableProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public bool DeepObservableProperty { get => _deepObservableProperty = _deepObservablePropertyHelper?.Value ?? _deepObservableProperty; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _deepObservablePropertyHelper = DeepObservable!.ToProperty(this, nameof(DeepObservableProperty));
        }
    }
}
}
}

}
#nullable restore
#pragma warning restore