//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_elapsedHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.TimeSpan> _elapsedHelper;

        /// <inheritdoc cref="_elapsed"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.TimeSpan Elapsed { get => _elapsed = _elapsedHelper?.Value ?? _elapsed; }
        /// <inheritdoc cref="_lastUpdatedHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.DateTimeOffset> _lastUpdatedHelper;

        /// <inheritdoc cref="_lastUpdated"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.DateTimeOffset LastUpdated { get => _lastUpdated = _lastUpdatedHelper?.Value ?? _lastUpdated; }
        /// <inheritdoc cref="_remainingTimeHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.TimeSpan?> _remainingTimeHelper;

        /// <inheritdoc cref="_remainingTime"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.TimeSpan? RemainingTime { get => _remainingTime = (_remainingTimeHelper == null ? _remainingTime : _remainingTimeHelper.Value); }
    }
}
#nullable restore
#pragma warning restore