//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_currentItemHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::TestNs.IItem?> _currentItemHelper;

        /// <inheritdoc cref="_currentItem"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.IItem? CurrentItem { get => _currentItem = (_currentItemHelper == null ? _currentItem : _currentItemHelper.Value); }
        /// <inheritdoc cref="_subscriptionHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.IDisposable?> _subscriptionHelper;

        /// <inheritdoc cref="_subscription"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.IDisposable? Subscription { get => _subscription = (_subscriptionHelper == null ? _subscription : _subscriptionHelper.Value); }
        /// <inheritdoc cref="_allItemsHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.Collections.Generic.IReadOnlyCollection<global::TestNs.IItem>?> _allItemsHelper;

        /// <inheritdoc cref="_allItems"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.Generic.IReadOnlyCollection<global::TestNs.IItem>? AllItems { get => _allItems = (_allItemsHelper == null ? _allItems : _allItemsHelper.Value); }
    }
}
#nullable restore
#pragma warning restore