//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_formatterHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.Func<int, string>?> _formatterHelper;

        /// <inheritdoc cref="_formatter"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Func<int, string>? Formatter { get => _formatter = (_formatterHelper == null ? _formatter : _formatterHelper.Value); }
        /// <inheritdoc cref="_callbackHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.Action?> _callbackHelper;

        /// <inheritdoc cref="_callback"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Action? Callback { get => _callback = (_callbackHelper == null ? _callback : _callbackHelper.Value); }
        /// <inheritdoc cref="_handlerHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.EventHandler?> _handlerHelper;

        /// <inheritdoc cref="_handler"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.EventHandler? Handler { get => _handler = (_handlerHelper == null ? _handler : _handlerHelper.Value); }
    }
}
#nullable restore
#pragma warning restore