//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_nullableIntHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int?> _nullableIntHelper;

        /// <inheritdoc cref="_nullableInt"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int? NullableInt { get => _nullableInt = (_nullableIntHelper == null ? _nullableInt : _nullableIntHelper.Value); }
        /// <inheritdoc cref="_nullableDateTimeHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.DateTime?> _nullableDateTimeHelper;

        /// <inheritdoc cref="_nullableDateTime"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.DateTime? NullableDateTime { get => _nullableDateTime = (_nullableDateTimeHelper == null ? _nullableDateTime : _nullableDateTimeHelper.Value); }
        /// <inheritdoc cref="_nullableGuidHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::System.Guid?> _nullableGuidHelper;

        /// <inheritdoc cref="_nullableGuid"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Guid? NullableGuid { get => _nullableGuid = (_nullableGuidHelper == null ? _nullableGuid : _nullableGuidHelper.Value); }
    }
}
#nullable restore
#pragma warning restore