//HintName: TestNs.Level1+Level2+Level3+Level4.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class Level1
{
public partial class Level2
{
public partial class Level3
{

    public partial class Level4
    {
        /// <inheritdoc cref="_level4ValueHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _level4ValueHelper;

        /// <inheritdoc cref="_level4Value"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Level4Value { get => _level4Value = _level4ValueHelper?.Value ?? _level4Value; }
    }
}
}
}

}
#nullable restore
#pragma warning restore