//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="InternalStateProperty"/>
        private string _internalStateProperty;

        /// <inheritdoc cref="_internalStatePropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<string>? _internalStatePropertyHelper;

        /// <inheritdoc cref="_internalStateProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Runtime.Serialization.IgnoreDataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonIgnoreAttribute()]
        public string InternalStateProperty { get => _internalStateProperty = _internalStatePropertyHelper?.Value ?? _internalStateProperty; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _internalStatePropertyHelper = InternalState!.ToProperty(this, nameof(InternalStateProperty));
        }
    }
}
#nullable restore
#pragma warning restore