//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="HasItemsProperty"/>
        private bool _hasItemsProperty;

        /// <inheritdoc cref="_hasItemsPropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<bool>? _hasItemsPropertyHelper;

        /// <inheritdoc cref="_hasItemsProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public bool HasItemsProperty { get => _hasItemsProperty = _hasItemsPropertyHelper?.Value ?? _hasItemsProperty; }
/// <inheritdoc cref="DisplayNameProperty"/>
        private string _displayNameProperty;

        /// <inheritdoc cref="_displayNamePropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<string>? _displayNamePropertyHelper;

        /// <inheritdoc cref="_displayNameProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string DisplayNameProperty { get => _displayNameProperty = _displayNamePropertyHelper?.Value ?? _displayNameProperty; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _hasItemsPropertyHelper = HasItems!.ToProperty(this, nameof(HasItemsProperty));
            _displayNamePropertyHelper = DisplayName()!.ToProperty(this, nameof(DisplayNameProperty));
        }
    }
}
#nullable restore
#pragma warning restore