//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_computedValueHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _computedValueHelper;

        /// <inheritdoc cref="_computedValue"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonPropertyNameAttribute("computed_value")]
        [global::System.Text.Json.Serialization.JsonIncludeAttribute()]
        public int ComputedValue { get => _computedValue = _computedValueHelper?.Value ?? _computedValue; }
    }
}
#nullable restore
#pragma warning restore