//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_bytesHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<byte[]?> _bytesHelper;

        /// <inheritdoc cref="_bytes"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public byte[]? Bytes { get => _bytes = (_bytesHelper == null ? _bytes : _bytesHelper.Value); }
        /// <inheritdoc cref="_stringsHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<string[]?> _stringsHelper;

        /// <inheritdoc cref="_strings"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string[]? Strings { get => _strings = (_stringsHelper == null ? _strings : _stringsHelper.Value); }
        /// <inheritdoc cref="_jaggedArrayHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int[][]?> _jaggedArrayHelper;

        /// <inheritdoc cref="_jaggedArray"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int[][]? JaggedArray { get => _jaggedArray = (_jaggedArrayHelper == null ? _jaggedArray : _jaggedArrayHelper.Value); }
    }
}
#nullable restore
#pragma warning restore