//HintName: TestNs.Level1+Level2.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class Level1
{

    public partial class Level2
    {
        /// <inheritdoc cref="_level2ValueHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _level2ValueHelper;

        /// <inheritdoc cref="_level2Value"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Level2Value { get => _level2Value = _level2ValueHelper?.Value ?? _level2Value; }
    }
}

}
#nullable restore
#pragma warning restore