//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="IsLoading"/>
        private bool _isLoading;

        /// <inheritdoc cref="_isLoadingHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<bool>? _isLoadingHelper;

        /// <inheritdoc cref="_isLoading"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public bool IsLoading { get => _isLoading = _isLoadingHelper?.Value ?? _isLoading; }
/// <inheritdoc cref="ErrorMessage"/>
        private string? _errorMessage;

        /// <inheritdoc cref="_errorMessageHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<string?>? _errorMessageHelper;

        /// <inheritdoc cref="_errorMessage"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? ErrorMessage { get => _errorMessage = (_errorMessageHelper == null ? _errorMessage : _errorMessageHelper.Value); }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _isLoadingHelper = GetLoadingState()!.ToProperty(this, nameof(IsLoading));
            _errorMessageHelper = GetError()!.ToProperty(this, nameof(ErrorMessage));
        }
    }
}
#nullable restore
#pragma warning restore