//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="ComplexDataObservableProperty"/>
        private global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<int>> _complexDataObservableProperty;

        /// <inheritdoc cref="_complexDataObservablePropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<int>>>? _complexDataObservablePropertyHelper;

        /// <inheritdoc cref="_complexDataObservableProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<int>> ComplexDataObservableProperty { get => _complexDataObservableProperty = _complexDataObservablePropertyHelper?.Value ?? _complexDataObservableProperty; }
/// <inheritdoc cref="NestedReadOnlyObservableProperty"/>
        private global::System.Collections.Generic.IReadOnlyDictionary<int, global::System.Collections.Generic.IReadOnlyList<string>> _nestedReadOnlyObservableProperty;

        /// <inheritdoc cref="_nestedReadOnlyObservablePropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<global::System.Collections.Generic.IReadOnlyDictionary<int, global::System.Collections.Generic.IReadOnlyList<string>>>? _nestedReadOnlyObservablePropertyHelper;

        /// <inheritdoc cref="_nestedReadOnlyObservableProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.Generic.IReadOnlyDictionary<int, global::System.Collections.Generic.IReadOnlyList<string>> NestedReadOnlyObservableProperty { get => _nestedReadOnlyObservableProperty = _nestedReadOnlyObservablePropertyHelper?.Value ?? _nestedReadOnlyObservableProperty; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _complexDataObservablePropertyHelper = ComplexDataObservable!.ToProperty(this, nameof(ComplexDataObservableProperty));
            _nestedReadOnlyObservablePropertyHelper = NestedReadOnlyObservable!.ToProperty(this, nameof(NestedReadOnlyObservableProperty));
        }
    }
}
#nullable restore
#pragma warning restore