//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="GetLoadingStateProperty"/>
        private bool _getLoadingStateProperty;

        /// <inheritdoc cref="_getLoadingStatePropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<bool>? _getLoadingStatePropertyHelper;

        /// <inheritdoc cref="_getLoadingStateProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public bool GetLoadingStateProperty { get => _getLoadingStateProperty = _getLoadingStatePropertyHelper?.Value ?? _getLoadingStateProperty; }
/// <inheritdoc cref="GetErrorProperty"/>
        private string? _getErrorProperty;

        /// <inheritdoc cref="_getErrorPropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<string?>? _getErrorPropertyHelper;

        /// <inheritdoc cref="_getErrorProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? GetErrorProperty { get => _getErrorProperty = (_getErrorPropertyHelper == null ? _getErrorProperty : _getErrorPropertyHelper.Value); }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _getLoadingStatePropertyHelper = GetLoadingState()!.ToProperty(this, nameof(GetLoadingStateProperty));
            _getErrorPropertyHelper = GetError()!.ToProperty(this, nameof(GetErrorProperty));
        }
    }
}
#nullable restore
#pragma warning restore