//HintName: TestNs.Level1.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class Level1
    {
        /// <inheritdoc cref="_level1ValueHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _level1ValueHelper;

        /// <inheritdoc cref="_level1Value"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Level1Value { get => _level1Value = _level1ValueHelper?.Value ?? _level1Value; }
    }
}
#nullable restore
#pragma warning restore