//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_statusHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::TestNs.Status> _statusHelper;

        /// <inheritdoc cref="_status"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.Status Status { get => _status = _statusHelper?.Value ?? _status; }
        /// <inheritdoc cref="_nullableStatusHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<global::TestNs.Status?> _nullableStatusHelper;

        /// <inheritdoc cref="_nullableStatus"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.Status? NullableStatus { get => _nullableStatus = (_nullableStatusHelper == null ? _nullableStatus : _nullableStatusHelper.Value); }
    }
}
#nullable restore
#pragma warning restore