//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_countHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _countHelper;

        /// <inheritdoc cref="_count"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Count { get => _count = _countHelper?.Value ?? _count; }
        /// <inheritdoc cref="_percentageHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<double> _percentageHelper;

        /// <inheritdoc cref="_percentage"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public double Percentage { get => _percentage = _percentageHelper?.Value ?? _percentage; }
    }
}
#nullable restore
#pragma warning restore