//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="ResultObservableProperty"/>
        private global::TestNs.IResult? _resultObservableProperty;

        /// <inheritdoc cref="_resultObservablePropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<global::TestNs.IResult?>? _resultObservablePropertyHelper;

        /// <inheritdoc cref="_resultObservableProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::TestNs.IResult? ResultObservableProperty { get => _resultObservableProperty = (_resultObservablePropertyHelper == null ? _resultObservableProperty : _resultObservablePropertyHelper.Value); }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _resultObservablePropertyHelper = ResultObservable!.ToProperty(this, nameof(ResultObservableProperty));
        }
    }
}
#nullable restore
#pragma warning restore