//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_statusHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<string> _statusHelper;

        /// <inheritdoc cref="_status"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string Status { get => _status = _statusHelper?.Value ?? _status; }
    }
}
#nullable restore
#pragma warning restore