//HintName: TestNs.Level1+Level2.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class Level1
{

    public partial class Level2
    {
        /// <inheritdoc cref="Level2ObservableProperty"/>
        private string _level2ObservableProperty;

        /// <inheritdoc cref="_level2ObservablePropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<string>? _level2ObservablePropertyHelper;

        /// <inheritdoc cref="_level2ObservableProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string Level2ObservableProperty { get => _level2ObservableProperty = _level2ObservablePropertyHelper?.Value ?? _level2ObservableProperty; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _level2ObservablePropertyHelper = Level2Observable!.ToProperty(this, nameof(Level2ObservableProperty));
        }
    }
}

}
#nullable restore
#pragma warning restore