//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="Test3Property"/>
        private int _test3Property;

        /// <inheritdoc cref="_test3PropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<int>? _test3PropertyHelper;

        /// <inheritdoc cref="_test3Property"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test3Property { get => _test3Property = _test3PropertyHelper?.Value ?? _test3Property; }

        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _test3PropertyHelper = Test3()!.ToProperty(this, nameof(Test3Property));
        }
    }
}
#nullable restore
#pragma warning restore