//HintName: TestNs.TestVM+TestVMInner2+TestVMInner3.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class TestVM
{
public partial class TestVMInner2
{

    public partial class TestVMInner3
    {
        /// <inheritdoc cref="TestIn3Property"/>
        private int _testIn3Property;

        /// <inheritdoc cref="_testIn3PropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<int>? _testIn3PropertyHelper;

        /// <inheritdoc cref="_testIn3Property"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestIn3Property { get => _testIn3Property = _testIn3PropertyHelper?.Value ?? _testIn3Property; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _testIn3PropertyHelper = TestIn3!.ToProperty(this, nameof(TestIn3Property));
        }
    }
}
}

}
#nullable restore
#pragma warning restore