//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
using ReactiveUI;
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    /// <inheritdoc/>
    partial class TestVM
    {
        /// <inheritdoc cref="Test2Property"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "1.1.0.0")]
        private int _test2Property;
        /// <inheritdoc cref="_test2PropertyHelper"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "1.1.0.0")]
        private ReactiveUI.ObservableAsPropertyHelper<int>? _test2PropertyHelper;
        /// <inheritdoc cref="_test2Property"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "1.1.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test2Property { get => _test2Property = _test2PropertyHelper?.Value ?? _test2Property; }

        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "1.1.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _test2PropertyHelper = Test2()!.ToProperty(this, nameof(Test2Property));
        }
    }
}