//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the TestVM which contains ReactiveUI Observable As Property initialization.
    /// </summary>
    public partial class TestVM
    {
        /// <inheritdoc cref="Test4Property"/>
        private int _test4Property;

        /// <inheritdoc cref="_test4PropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<int>? _test4PropertyHelper;

        /// <inheritdoc cref="_test4Property"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test4Property { get => _test4Property = _test4PropertyHelper?.Value ?? _test4Property; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _test4PropertyHelper = Test4!.ToProperty(this, nameof(Test4Property));
        }
    }
}
#nullable restore
#pragma warning restore