//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="PLCActive"/>
        private string _pLCActive = "";

        /// <inheritdoc cref="_pLCActiveHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<string> _pLCActiveHelper;

        /// <inheritdoc cref="_pLCActive"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial string PLCActive { get => _pLCActive = (_pLCActiveHelper == null ? _pLCActive : _pLCActiveHelper.Value); }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            
        }
    }
}
#nullable restore
#pragma warning restore