//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="MyNamedProperty"/>
        private int _myNamedProperty;

        /// <inheritdoc cref="_myNamedPropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<int>? _myNamedPropertyHelper;

        /// <inheritdoc cref="_myNamedProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Text.Json.Serialization.JsonIncludeAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonIncludeAttribute()]
        public int MyNamedProperty { get => _myNamedProperty = _myNamedPropertyHelper?.Value ?? _myNamedProperty; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _myNamedPropertyHelper = Test5!.ToProperty(this, nameof(MyNamedProperty));
        }
    }
}
#nullable restore
#pragma warning restore