//HintName: TestNs.TestVM+TestVMInner1.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class TestVM
{

    public partial class TestVMInner1
    {
        /// <inheritdoc cref="TestIn1Property"/>
        private int _testIn1Property;

        /// <inheritdoc cref="_testIn1PropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<int>? _testIn1PropertyHelper;

        /// <inheritdoc cref="_testIn1Property"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestIn1Property { get => _testIn1Property = _testIn1PropertyHelper?.Value ?? _testIn1Property; }

        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _testIn1PropertyHelper = TestIn1!.ToProperty(this, nameof(TestIn1Property));
        }
    }
}

}
#nullable restore
#pragma warning restore