//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="Test6Property"/>
        private object _test6Property;

        /// <inheritdoc cref="_test6PropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<object>? _test6PropertyHelper;

        /// <inheritdoc cref="_test6Property"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonIncludeAttribute()]
        public object Test6Property { get => _test6Property = _test6PropertyHelper?.Value ?? _test6Property; }

        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _test6PropertyHelper = Test6!.ToProperty(this, nameof(Test6Property));
        }
    }
}
#nullable restore
#pragma warning restore