//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="PLCActive"/>
        private string _pLCActive = string.Empty;

        /// <inheritdoc cref="_pLCActiveHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<string> _pLCActiveHelper;

        /// <inheritdoc cref="_pLCActive"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial string PLCActive { get => _pLCActive = (_pLCActiveHelper == null ? _pLCActive : _pLCActiveHelper.Value); }
/// <inheritdoc cref="PLCName"/>
        private string? _pLCName;

        /// <inheritdoc cref="_pLCNameHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<string?> _pLCNameHelper;

        /// <inheritdoc cref="_pLCName"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial string? PLCName { get => _pLCName = (_pLCNameHelper == null ? _pLCName : _pLCNameHelper.Value); }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            
        }
    }
}
#nullable restore
#pragma warning restore