//HintName: TestNs.TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the TestVM which contains ReactiveUI Observable As Property initialization.
    /// </summary>
    public partial class TestVM
    {
        /// <inheritdoc cref="Test2Property"/>
        private int _test2Property;

        /// <inheritdoc cref="_test2PropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<int>? _test2PropertyHelper;

        /// <inheritdoc cref="_test2Property"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.2.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test2Property { get => _test2Property = _test2PropertyHelper?.Value ?? _test2Property; }

        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.2.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _test2PropertyHelper = Test2()!.ToProperty(this, nameof(Test2Property));
        }
    }
}
#nullable restore
#pragma warning restore