//HintName: TestNs.TestVM+TestVMInner2.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class TestVM
{
/// <summary>
    /// Partial class for the TestVMInner2 which contains ReactiveUI Observable As Property initialization.
    /// </summary>
    public partial class TestVMInner2
    {
        /// <inheritdoc cref="TestIn2Property"/>
        private int _testIn2Property;

        /// <inheritdoc cref="_testIn2PropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<int>? _testIn2PropertyHelper;

        /// <inheritdoc cref="_testIn2Property"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestIn2Property { get => _testIn2Property = _testIn2PropertyHelper?.Value ?? _testIn2Property; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _testIn2PropertyHelper = TestIn2!.ToProperty(this, nameof(TestIn2Property));
        }
    }
}

}
#nullable restore
#pragma warning restore