//HintName: TestNs.TestVM+TestVMInner1.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace TestNs
{
    public partial class TestVM
{
/// <summary>
    /// Partial class for the TestVMInner1 which contains ReactiveUI Observable As Property initialization.
    /// </summary>
    public partial class TestVMInner1
    {
        /// <inheritdoc cref="TestIn1Property"/>
        private int _testIn1Property;

        /// <inheritdoc cref="_testIn1PropertyHelper"/>
        private ReactiveUI.ObservableAsPropertyHelper<int>? _testIn1PropertyHelper;

        /// <inheritdoc cref="_testIn1Property"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestIn1Property { get => _testIn1Property = _testIn1PropertyHelper?.Value ?? _testIn1Property; }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        protected void InitializeOAPH()
        {
            _testIn1PropertyHelper = TestIn1!.ToProperty(this, nameof(TestIn1Property));
        }
    }
}

}
#nullable restore
#pragma warning restore