//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    /// <summary>
    /// Partial class for the TestVM which contains ReactiveUI Observable As Property initialization.
    /// </summary>
    public partial class TestVM
    {
        /// <inheritdoc cref="_testPropertyHelper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<double?> _testPropertyHelper;

        /// <inheritdoc cref="_testProperty"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.Text.Json.Serialization.JsonIncludeAttribute()]
        public double? TestProperty { get => _testProperty = (_testPropertyHelper == null ? _testProperty : _testPropertyHelper.Value); }
    }
}
#nullable restore
#pragma warning restore