//HintName: TestNs.TestVM+TestVMInner1.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class TestVM
{

    public partial class TestVMInner1
    {
        /// <inheritdoc cref="_testIn1Helper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _testIn1Helper;

        /// <inheritdoc cref="_testIn1"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestIn1 { get => _testIn1 = _testIn1Helper?.Value ?? _testIn1; }
    }
}

}
#nullable restore
#pragma warning restore