//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_test4Helper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _test4Helper;

        /// <inheritdoc cref="_test4"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test4 { get => _test4 = _test4Helper?.Value ?? _test4; }
    }
}
#nullable restore
#pragma warning restore