//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    /// <summary>
    /// Partial class for the TestVM which contains ReactiveUI Observable As Property initialization.
    /// </summary>
    public partial class TestVM
    {
        /// <inheritdoc cref="_test3Helper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _test3Helper;

        /// <inheritdoc cref="_test3"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.2.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test3 { get => _test3 = _test3Helper?.Value ?? _test3; }
    }
}
#nullable restore
#pragma warning restore