//HintName: TestNs.TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_test5Helper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _test5Helper;

        /// <inheritdoc cref="_test5"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test5 { get => _test5 = _test5Helper?.Value ?? _test5; }
    }
}
#nullable restore
#pragma warning restore