//HintName: TestNs.TestVM+TestVMInner2.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class TestVM
{

    public partial class TestVMInner2
    {
        /// <inheritdoc cref="_testIn2Helper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _testIn2Helper;

        /// <inheritdoc cref="_testIn2"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "2.3.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int TestIn2 { get => _testIn2 = _testIn2Helper?.Value ?? _testIn2; }
    }
}

}
#nullable restore
#pragma warning restore