//HintName: TestVM.ObservableAsProperties.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace TestNs
{
    /// <inheritdoc/>
    public partial class TestVM
    {
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "1.1.0.0")]
        /// <inheritdoc cref="_test1Helper"/>
        private readonly ReactiveUI.ObservableAsPropertyHelper<int> _test1Helper;

        /// <inheritdoc cref="_test1"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int Test1 { get => _test1 = _test1Helper?.Value ?? _test1; }
    }
}
#nullable restore
#pragma warning restore