//HintName: TestNs.OuterVM+InnerVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class OuterVM
    {
        public partial class InnerVM
        {
            private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _innerCollectionCollectionChangedHandler;

            /// <inheritdoc cref="_innerCollection"/>
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            public global::System.Collections.ObjectModel.ObservableCollection<string>? InnerCollection
            {
                get => _innerCollection;
                set
                {
                    var handler = _innerCollectionCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(InnerCollection));
                    if (_innerCollection != null)
                    {
                        _innerCollection.CollectionChanged -= handler;
                    }

                    _innerCollection = value;
                    this.RaisePropertyChanged(nameof(InnerCollection));

                    if (value != null)
                    {
                        value.CollectionChanged += handler;
                    }
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
