//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_ids"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<global::System.Guid>? Ids
        {
            get => _ids;
            set
            {
                if (value == null)
                {
                    Ids.CollectionChanged -= CollectionChanged(this, nameof(Ids));
                }

                _ids = value;
                this.RaisePropertyChanged(nameof(Ids));

                if (_ids != null)
                {
                    // Remove the old handler if it exists
                    Ids.CollectionChanged -= CollectionChanged(this, nameof(Ids));

                    Ids.CollectionChanged += CollectionChanged(this, nameof(Ids));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore