//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_points"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<global::TestNs.Point>? Points
        {
            get => _points;
            set
            {
                if (value == null)
                {
                    Points.CollectionChanged -= CollectionChanged(this, nameof(Points));
                }

                _points = value;
                this.RaisePropertyChanged(nameof(Points));

                if (_points != null)
                {
                    // Remove the old handler if it exists
                    Points.CollectionChanged -= CollectionChanged(this, nameof(Points));

                    Points.CollectionChanged += CollectionChanged(this, nameof(Points));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore