//HintName: TestNs.OuterVM+InnerVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class OuterVM
{

    public partial class InnerVM
    {
        /// <inheritdoc cref="_innerCollection"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<string>? InnerCollection
        {
            get => _innerCollection;
            set
            {
                if (value == null)
                {
                    InnerCollection.CollectionChanged -= CollectionChanged(this, nameof(InnerCollection));
                }

                _innerCollection = value;
                this.RaisePropertyChanged(nameof(InnerCollection));

                if (_innerCollection != null)
                {
                    // Remove the old handler if it exists
                    InnerCollection.CollectionChanged -= CollectionChanged(this, nameof(InnerCollection));

                    InnerCollection.CollectionChanged += CollectionChanged(this, nameof(InnerCollection));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}

}
#nullable restore
#pragma warning restore