//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class TestVM
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _nullableStringsCollectionChangedHandler;

        /// <inheritdoc cref="_nullableStrings"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<string?>? NullableStrings
        {
            get => _nullableStrings;
            set
            {
                var handler = _nullableStringsCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(NullableStrings));
                if (_nullableStrings != null)
                {
                    _nullableStrings.CollectionChanged -= handler;
                }

                _nullableStrings = value;
                this.RaisePropertyChanged(nameof(NullableStrings));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }

        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _nullableIntsCollectionChangedHandler;

        /// <inheritdoc cref="_nullableInts"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<int?>? NullableInts
        {
            get => _nullableInts;
            set
            {
                var handler = _nullableIntsCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(NullableInts));
                if (_nullableInts != null)
                {
                    _nullableInts.CollectionChanged -= handler;
                }

                _nullableInts = value;
                this.RaisePropertyChanged(nameof(NullableInts));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
