//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class TestVM
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _pointsCollectionChangedHandler;

        /// <inheritdoc cref="_points"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<global::TestNs.Point>? Points
        {
            get => _points;
            set
            {
                var handler = _pointsCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(Points));
                if (_points != null)
                {
                    _points.CollectionChanged -= handler;
                }

                _points = value;
                this.RaisePropertyChanged(nameof(Points));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
