//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_statuses"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<global::TestNs.Status>? Statuses
        {
            get => _statuses;
            set
            {
                if (value == null)
                {
                    Statuses.CollectionChanged -= CollectionChanged(this, nameof(Statuses));
                }

                _statuses = value;
                this.RaisePropertyChanged(nameof(Statuses));

                if (_statuses != null)
                {
                    // Remove the old handler if it exists
                    Statuses.CollectionChanged -= CollectionChanged(this, nameof(Statuses));

                    Statuses.CollectionChanged += CollectionChanged(this, nameof(Statuses));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore