//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class TestVM
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _idsCollectionChangedHandler;

        /// <inheritdoc cref="_ids"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<global::System.Guid>? Ids
        {
            get => _ids;
            set
            {
                var handler = _idsCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(Ids));
                if (_ids != null)
                {
                    _ids.CollectionChanged -= handler;
                }

                _ids = value;
                this.RaisePropertyChanged(nameof(Ids));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
