//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_items"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<string>? Items
        {
            get => _items;
            set
            {
                if (value == null)
                {
                    Items.CollectionChanged -= CollectionChanged(this, nameof(Items));
                }

                _items = value;
                this.RaisePropertyChanged(nameof(Items));

                if (_items != null)
                {
                    // Remove the old handler if it exists
                    Items.CollectionChanged -= CollectionChanged(this, nameof(Items));

                    Items.CollectionChanged += CollectionChanged(this, nameof(Items));
                }
            }
        }
        /// <inheritdoc cref="_selectedIds"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<int>? SelectedIds
        {
            get => _selectedIds;
            set
            {
                if (value == null)
                {
                    SelectedIds.CollectionChanged -= CollectionChanged(this, nameof(SelectedIds));
                }

                _selectedIds = value;
                this.RaisePropertyChanged(nameof(SelectedIds));

                if (_selectedIds != null)
                {
                    // Remove the old handler if it exists
                    SelectedIds.CollectionChanged -= CollectionChanged(this, nameof(SelectedIds));

                    SelectedIds.CollectionChanged += CollectionChanged(this, nameof(SelectedIds));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore