//HintName: TestNs.GenericVM`1.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class GenericVM<T>
    {
        /// <inheritdoc cref="_items"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<T>? Items
        {
            get => _items;
            set
            {
                if (value == null)
                {
                    Items.CollectionChanged -= CollectionChanged(this, nameof(Items));
                }

                _items = value;
                this.RaisePropertyChanged(nameof(Items));

                if (_items != null)
                {
                    // Remove the old handler if it exists
                    Items.CollectionChanged -= CollectionChanged(this, nameof(Items));

                    Items.CollectionChanged += CollectionChanged(this, nameof(Items));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore