//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_dates"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<global::System.DateTime>? Dates
        {
            get => _dates;
            set
            {
                if (value == null)
                {
                    Dates.CollectionChanged -= CollectionChanged(this, nameof(Dates));
                }

                _dates = value;
                this.RaisePropertyChanged(nameof(Dates));

                if (_dates != null)
                {
                    // Remove the old handler if it exists
                    Dates.CollectionChanged -= CollectionChanged(this, nameof(Dates));

                    Dates.CollectionChanged += CollectionChanged(this, nameof(Dates));
                }
            }
        }
        /// <inheritdoc cref="_timestamps"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<global::System.DateTimeOffset>? Timestamps
        {
            get => _timestamps;
            set
            {
                if (value == null)
                {
                    Timestamps.CollectionChanged -= CollectionChanged(this, nameof(Timestamps));
                }

                _timestamps = value;
                this.RaisePropertyChanged(nameof(Timestamps));

                if (_timestamps != null)
                {
                    // Remove the old handler if it exists
                    Timestamps.CollectionChanged -= CollectionChanged(this, nameof(Timestamps));

                    Timestamps.CollectionChanged += CollectionChanged(this, nameof(Timestamps));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore