//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class TestVM
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _binaryDataCollectionChangedHandler;

        /// <inheritdoc cref="_binaryData"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<byte[]>? BinaryData
        {
            get => _binaryData;
            set
            {
                var handler = _binaryDataCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(BinaryData));
                if (_binaryData != null)
                {
                    _binaryData.CollectionChanged -= handler;
                }

                _binaryData = value;
                this.RaisePropertyChanged(nameof(BinaryData));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
