//HintName: TestNs.GenericVM`1.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class GenericVM<T>
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _itemsCollectionChangedHandler;

        /// <inheritdoc cref="_items"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<T>? Items
        {
            get => _items;
            set
            {
                var handler = _itemsCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(Items));
                if (_items != null)
                {
                    _items.CollectionChanged -= handler;
                }

                _items = value;
                this.RaisePropertyChanged(nameof(Items));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
