//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class TestVM
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _statusesCollectionChangedHandler;

        /// <inheritdoc cref="_statuses"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<global::TestNs.Status>? Statuses
        {
            get => _statuses;
            set
            {
                var handler = _statusesCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(Statuses));
                if (_statuses != null)
                {
                    _statuses.CollectionChanged -= handler;
                }

                _statuses = value;
                this.RaisePropertyChanged(nameof(Statuses));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
