//HintName: Namespace2.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace Namespace2
{
    public partial class TestVM
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _namesCollectionChangedHandler;

        /// <inheritdoc cref="_names"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<string>? Names
        {
            get => _names;
            set
            {
                var handler = _namesCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(Names));
                if (_names != null)
                {
                    _names.CollectionChanged -= handler;
                }

                _names = value;
                this.RaisePropertyChanged(nameof(Names));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
