//HintName: Namespace1.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace Namespace1
{
    public partial class TestVM
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _numbersCollectionChangedHandler;

        /// <inheritdoc cref="_numbers"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<int>? Numbers
        {
            get => _numbers;
            set
            {
                var handler = _numbersCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(Numbers));
                if (_numbers != null)
                {
                    _numbers.CollectionChanged -= handler;
                }

                _numbers = value;
                this.RaisePropertyChanged(nameof(Numbers));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
