//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_nullableStrings"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<string?>? NullableStrings
        {
            get => _nullableStrings;
            set
            {
                if (value == null)
                {
                    NullableStrings.CollectionChanged -= CollectionChanged(this, nameof(NullableStrings));
                }

                _nullableStrings = value;
                this.RaisePropertyChanged(nameof(NullableStrings));

                if (_nullableStrings != null)
                {
                    // Remove the old handler if it exists
                    NullableStrings.CollectionChanged -= CollectionChanged(this, nameof(NullableStrings));

                    NullableStrings.CollectionChanged += CollectionChanged(this, nameof(NullableStrings));
                }
            }
        }
        /// <inheritdoc cref="_nullableInts"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<int?>? NullableInts
        {
            get => _nullableInts;
            set
            {
                if (value == null)
                {
                    NullableInts.CollectionChanged -= CollectionChanged(this, nameof(NullableInts));
                }

                _nullableInts = value;
                this.RaisePropertyChanged(nameof(NullableInts));

                if (_nullableInts != null)
                {
                    // Remove the old handler if it exists
                    NullableInts.CollectionChanged -= CollectionChanged(this, nameof(NullableInts));

                    NullableInts.CollectionChanged += CollectionChanged(this, nameof(NullableInts));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore