//HintName: TestNs.OuterVM+InnerVM+DeepInnerVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class OuterVM
    {
        public partial class InnerVM
        {
            public partial class DeepInnerVM
            {
                private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _deepCollectionCollectionChangedHandler;

                /// <inheritdoc cref="_deepCollection"/>
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public global::System.Collections.ObjectModel.ObservableCollection<double>? DeepCollection
                {
                    get => _deepCollection;
                    set
                    {
                        var handler = _deepCollectionCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(DeepCollection));
                        if (_deepCollection != null)
                        {
                            _deepCollection.CollectionChanged -= handler;
                        }

                        _deepCollection = value;
                        this.RaisePropertyChanged(nameof(DeepCollection));

                        if (value != null)
                        {
                            value.CollectionChanged += handler;
                        }
                    }
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
