//HintName: TestNs.OuterVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class OuterVM
    {
        /// <inheritdoc cref="_outerCollection"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<int>? OuterCollection
        {
            get => _outerCollection;
            set
            {
                if (value == null)
                {
                    OuterCollection.CollectionChanged -= CollectionChanged(this, nameof(OuterCollection));
                }

                _outerCollection = value;
                this.RaisePropertyChanged(nameof(OuterCollection));

                if (_outerCollection != null)
                {
                    // Remove the old handler if it exists
                    OuterCollection.CollectionChanged -= CollectionChanged(this, nameof(OuterCollection));

                    OuterCollection.CollectionChanged += CollectionChanged(this, nameof(OuterCollection));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore