//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class TestVM
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _namesCollectionChangedHandler;

        /// <inheritdoc cref="_names"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<string>? Names
        {
            get => _names;
            set
            {
                var handler = _namesCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(Names));
                if (_names != null)
                {
                    _names.CollectionChanged -= handler;
                }

                _names = value;
                this.RaisePropertyChanged(nameof(Names));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }

        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _numbersCollectionChangedHandler;

        /// <inheritdoc cref="_numbers"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<int>? Numbers
        {
            get => _numbers;
            set
            {
                var handler = _numbersCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(Numbers));
                if (_numbers != null)
                {
                    _numbers.CollectionChanged -= handler;
                }

                _numbers = value;
                this.RaisePropertyChanged(nameof(Numbers));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }

        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _valuesCollectionChangedHandler;

        /// <inheritdoc cref="_values"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<double>? Values
        {
            get => _values;
            set
            {
                var handler = _valuesCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(Values));
                if (_values != null)
                {
                    _values.CollectionChanged -= handler;
                }

                _values = value;
                this.RaisePropertyChanged(nameof(Values));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
