//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    public partial class TestVM
    {
        private global::System.Collections.Specialized.NotifyCollectionChangedEventHandler? _publicObservableCollectionTestCollectionChangedHandler;

        /// <inheritdoc cref="_publicObservableCollectionTest"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<int>? PublicObservableCollectionTest
        {
            get => _publicObservableCollectionTest;
            set
            {
                var handler = _publicObservableCollectionTestCollectionChangedHandler ??= (_, _) => this.RaisePropertyChanged(nameof(PublicObservableCollectionTest));
                if (_publicObservableCollectionTest != null)
                {
                    _publicObservableCollectionTest.CollectionChanged -= handler;
                }

                _publicObservableCollectionTest = value;
                this.RaisePropertyChanged(nameof(PublicObservableCollectionTest));

                if (value != null)
                {
                    value.CollectionChanged += handler;
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
