//HintName: TestNs.TestVM.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial class TestVM
    {
        /// <inheritdoc cref="_tuples"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<(int Id, string Name)>? Tuples
        {
            get => _tuples;
            set
            {
                if (value == null)
                {
                    Tuples.CollectionChanged -= CollectionChanged(this, nameof(Tuples));
                }

                _tuples = value;
                this.RaisePropertyChanged(nameof(Tuples));

                if (_tuples != null)
                {
                    // Remove the old handler if it exists
                    Tuples.CollectionChanged -= CollectionChanged(this, nameof(Tuples));

                    Tuples.CollectionChanged += CollectionChanged(this, nameof(Tuples));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore