//HintName: TestNs.TestVMRecord.ReactiveCollections.g.cs
// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable
namespace TestNs
{
    
    public partial record TestVMRecord
    {
        /// <inheritdoc cref="_numbers"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<int>? Numbers
        {
            get => _numbers;
            set
            {
                if (value == null)
                {
                    Numbers.CollectionChanged -= CollectionChanged(this, nameof(Numbers));
                }

                _numbers = value;
                this.RaisePropertyChanged(nameof(Numbers));

                if (_numbers != null)
                {
                    // Remove the old handler if it exists
                    Numbers.CollectionChanged -= CollectionChanged(this, nameof(Numbers));

                    Numbers.CollectionChanged += CollectionChanged(this, nameof(Numbers));
                }
            }
        }
        /// <inheritdoc cref="_names"/>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::System.Collections.ObjectModel.ObservableCollection<string>? Names
        {
            get => _names;
            set
            {
                if (value == null)
                {
                    Names.CollectionChanged -= CollectionChanged(this, nameof(Names));
                }

                _names = value;
                this.RaisePropertyChanged(nameof(Names));

                if (_names != null)
                {
                    // Remove the old handler if it exists
                    Names.CollectionChanged -= CollectionChanged(this, nameof(Names));

                    Names.CollectionChanged += CollectionChanged(this, nameof(Names));
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        private static global::System.Collections.Specialized.NotifyCollectionChangedEventHandler CollectionChanged(IReactiveObject @this, string propName)=> (_, _) =>  @this.RaisePropertyChanged(propName);
    }
}
#nullable restore
#pragma warning restore